### ISSUE TITLE
XP value multiplication with clumps

### ISSUE THREAD

**Issue by jklw10** [Globox1997/RpgDifficulty#30] opened 2022-07-15 10:39 UTC
supposedly clumps overwrites xp code (and so does mc dungeons)
so there would need to be compatability between these mods.

see similar issue posted to mc dungeons armors mod's github
https://github.com/chronosacaria/MCDungeonsArmors/issues/47

**Comment by chronosacaria** [comment] 2022-07-18 14:36
Hey, @jklw10, Globox can correct me if I am wrong, but, at least from MCDW's and MCDA's side of things, we don't overwrite anything having to do with the XP code. We make use of the Vanilla XP orbs for any of the abilities that use them. Judging by what I've seen with RpgDifficulty's code, it looks like this mod increases the amount of orbs dropped, but does not overwrite any XP code either. The issue may be the same issue that we're experiencing with https://github.com/chronosacaria/MCDungeonsArmors/issues/47, which is that Clumps coverts all of the XP orbs in an area into a different kind of entity. We (the devs of MCDW and MCDA) are working with the developer of Clumps to see if there is anything that we can do to alleviate this issue, but trust me when I say that the issue is _almost certainly_ not on RpgDifficulty's end

**Comment by jklw10** [comment] 2022-07-19 07:03
hmm... well i've been testing and atleast when i had both mc dungeons and clumps the xp dropped never changed. But i have not tried with only clumps on...

**Comment by Globox1997** [comment] 2022-08-22 08:11
Would be great if you can test it :)

**Comment by chronosacaria** [comment] 2022-08-22 18:02
This issue was resolved on MCDA and MCDW's end with the following commits and will be released in the next update:
MCDA: https://github.com/chronosacaria/MCDungeonsArmors/commit/780f1fc87427883a10df5cacdd6f5fd23e5b7f6b
MCDW: https://github.com/chronosacaria/MCDungeonsWeapons/commit/e293f8eae6094246b69630dacb4849f0415a23f4

**Closed as completed** 2023-03-20 18:39 UTC
